
- job:
    name: chart-vendor-golangci-lint
    parent: golangci-lint
    vars:
      go_version: 1.23.1
      golangci_lint_version: 1.61.0
      golangci_lint_options: --timeout=5m

- job:
    name: chart-vendor-go
    parent: golang-go
    abstract: true
    vars:
      go_version: 1.23.1

- job:
    name: chart-vendor-integration-atmosphere
    parent: chart-vendor-go
    required-projects:
      - vexxhost/atmosphere
    vars:
      go_command: |
        run main.go --charts-root {{ ansible_env.HOME }}/{{ zuul.projects['github.com/vexxhost/atmosphere'].src_dir }}/charts --config-file {{ ansible_env.HOME }}/{{ zuul.projects['github.com/vexxhost/atmosphere'].src_dir }}/.charts.yml

- job:
    name: chart-vendor-integration-magnum-cluster-api
    parent: chart-vendor-go
    required-projects:
      - vexxhost/magnum-cluster-api
    vars:
      go_command: |
        run main.go --charts-root {{ ansible_env.HOME }}/{{ zuul.projects['github.com/vexxhost/magnum-cluster-api'].src_dir }}/magnum_cluster_api/charts --config-file {{ ansible_env.HOME }}/{{ zuul.projects['github.com/vexxhost/magnum-cluster-api'].src_dir }}/.charts.yml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - chart-vendor-golangci-lint
        - chart-vendor-integration-atmosphere
        - chart-vendor-integration-magnum-cluster-api
    gate:
      jobs:
        - chart-vendor-golangci-lint
        - chart-vendor-integration-atmosphere
        - chart-vendor-integration-magnum-cluster-api
